<?php

namespace Cinema\CinemaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HallRepository extends EntityRepository
{
}
