<?php

namespace Cinema\CinemaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketsalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsalesRepository extends EntityRepository
{
}
